#!/usr/bin/env bash

CURR_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$CURR_DIR" ]]; then CURR_DIR=$(pwd); fi
source "${CURR_DIR}/__groupme_common.sh"

if [[ -e $GROUPME_CONFIG ]]; then
    source $GROUPME_CONFIG
else
    printf "Give me your API token\n"
    read API_TOKEN
    echo "GROUPME_TOKEN=$API_TOKEN" >> $GROUPME_CONFIG
fi
