#!/usr/bin/env bash

CURR_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$CURR_DIR" ]]; then CURR_DIR=$(pwd); fi
source "${CURR_DIR}/__groupme_common.sh"

hasConfig || exit $!
source "$GROUPME_CONFIG"

INTERACTIVE="false"
MSG=""
while getopts im: opt
do
    case "${opt}" in 
        i) INTERACTIVE="true";;
        m) MSG="${OPTARG}";;
    esac
done

function sendMessage() {
    local in="$1"
    local guid=""
    guid="$(uuidgen)"
    local msg="{\"message\": {\"source_guid\": \"$guid\", \"text\": \"$in\"}}"
    silence="$(curl --silent $GROUPME_API_BASE/groups/$GROUPME_GROUP_ID/messages?token=$GROUPME_TOKEN -H "Content-Type: application/json" -d "$msg")"
}

if [[ "true" = "$INTERACTIVE" ]]; then
    while true; do
        read -r IN
        if [[ "$IN" == "/q" ]]; then
            break
        elif [[ "$IN" == "" ]]; then
            continue
        fi
        IN="$(_escape "$IN")"
        sendMessage "$IN"
        IN=""
    done
else
    sendMessage "$MSG"
fi
