#!/usr/bin/env bash

CURR_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$CURR_DIR" ]]; then CURR_DIR=$(pwd); fi
source "${CURR_DIR}/__groupme_common.sh"


hasConfig || $!

sed -i '/.*GROUPME_GROUP_ID.*/d' "$GROUPME_CONFIG" 
