#!/usr/bin/bash

EXECS=(
    groupme-login 
    groupme-logout
    groupme-join
    groupme-leave
    groupme-listen
    groupme-message
)

DOCS=(
    groupme-shell.1
    groupme-message.1
)

for f in "${EXECS[@]}"; do
    DEST="/usr/local/bin/$f"
    printf "Installing $DEST.....\n"
    rm -f $DEST
    touch $DEST
    cat $(pwd)/_common.sh >> $DEST
    cat $(pwd)/$f >> $DEST
    chmod 755 $DEST
done

for f in "${DOCS[@]}"; do
    DEST="/usr/share/man/man1/$f"
    printf "Copying man pages to $DEST\n"
    rm -f $DEST
    ln -s $(pwd)/$f $DEST
done
