#!/usr/bin/env bash

EXECS=(
    groupme-login 
    groupme-logout
    groupme-join
    groupme-leave
    groupme-listen
    groupme-message
)

for f in "${EXECS[@]}"; do
    DEST="/usr/local/bin/$f"
    printf "Installing $DEST.....\n"
    touch $DEST
    echo "#!/usr/bin/env bash" > $DEST
    cat $(pwd)/_common.sh >> $DEST
    cat $(pwd)/$f >> $DEST
    chmod 755 $DEST
done
