#!/usr/bin/bash

EXECS=(
    __groupme_common.sh
    groupme-login 
    groupme-logout
    groupme-join
    groupme-leave
    groupme-listen
    groupme-message
)

DOCS=(
    groupme-shell.1
    groupme-message.1
)

for f in "${EXECS[@]}"; do
    DEST="/usr/local/bin/$f"
    printf "Removing %s.....\n" "$DEST"
    rm -f "$DEST"
done

for f in "${DOCS[@]}"; do 
    DEST="/usr/share/man/man1/$f"
    printf "Removing %s.....\n" "$DEST"
    rm -f "$DEST"
done
