#!/usr/bin/env bash

EXECS=(
    groupme-login 
    groupme-logout
    groupme-join
    groupme-leave
    groupme-listen
    groupme-message
)

DOCS=(
    groupme-shell.1
    groupme-message.1
)

for f in "${EXECS[@]}"; do
    DEST="/usr/local/bin/$f"
    printf "Removing $DEST.....\n"
    rm -f $DEST
done

for f in "${DOCS[@]}"; do 
    DEST="/usr/share/man/man1/$f"
    printf "Removing $DEST.....\n"
    rm -f $DEST
done
